//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class UCollege
    {
        public int Id { get; set; }
        public string CollegeName { get; set; }
        public int NoOfDepts { get; set; }
        public string PrincipalName { get; set; }
        public int UniversityId { get; set; }
    
        public virtual University University { get; set; }
    }
}
