//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmpNo { get; set; }
        public string EmpName { get; set; }
        public string Job { get; set; }
        public Nullable<int> Mgr { get; set; }
        public Nullable<System.DateTime> Hiredate { get; set; }
        public Nullable<decimal> Sal { get; set; }
        public Nullable<decimal> Comm { get; set; }
        public Nullable<int> DEPTNO { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
